include: package:very_good_analysis/analysis_options.5.0.0.yaml

# Config to exclude src/bindings.dart
analyzer:
  exclude:
    - lib/src/appkit_bindings.dart

linter:
  rules:
    public_member_api_docs: false